Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2022-10, with the labels that each got.

#52 COMDOX-346: Restore workflow customizations
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  package.json
  yarn.lock
Labels: enhancement

#53 Heading level fix
  src/pages/page-builder/viewports/add-breakpoints.md
Labels: editorial

#58 Update theme, link checker, yarn
  .github/workflows/test-pull-request.yml
  .yarn/releases/yarn-3.2.2.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, dependencies

#59 Editorial fixes
  src/pages/guide/css/index.md
Labels: editorial
