Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2022-08, with the labels that each got.

#31 Updated incorrect code sample
  src/pages/guide/validations/custom-rules.md
Labels: editorial

#33 Typo spotted
  src/pages/guide/translations/dictionary.md
Labels: editorial

#34 Bump aio-theme to 4.4.2
  package.json
  yarn.lock
Labels: dependencies

#37 Fix gramatical error
  src/pages/guide/css/ui-library.md
Labels: editorial

#38 Replace obsolete devdocs links
  src/pages/guide/caching.md
  src/pages/guide/css/critical-path.md
  src/pages/guide/css/debug.md
  src/pages/guide/css/index.md
  src/pages/guide/css/preprocess.md
  src/pages/guide/css/quickstart/index.md
  src/pages/guide/layouts/index.md
  src/pages/guide/templates/email-migration.md
  src/pages/guide/templates/walkthrough.md
  src/pages/guide/themes/apply-admin.md
  src/pages/guide/themes/apply-storefront.md
  src/pages/guide/themes/create-admin.md
  src/pages/guide/themes/create-storefront.md
  src/pages/guide/themes/install.md
  src/pages/guide/themes/js-bundling.md
  src/pages/guide/themes/structure.md
  src/pages/guide/themes/uninstall.md
  src/pages/guide/themes/workflow.md
  src/pages/guide/tools/grunt.md
  src/pages/guide/translations/dictionary.md
  src/pages/guide/translations/index.md
  src/pages/guide/translations/practice.md
  src/pages/guide/translations/theory.md
  src/pages/javascript/frontend-product-repository.md
  src/pages/javascript/index.md
  src/pages/javascript/jquery-widgets/alert.md
  src/pages/javascript/jquery-widgets/confirm.md
  src/pages/javascript/jquery-widgets/list.md
  src/pages/javascript/jquery-widgets/modal.md
  src/pages/javascript/jquery-widgets/prompt.md
  src/pages/ui-components/components/filters.md
  src/pages/ui-components/components/mass-actions.md
  src/pages/ui-components/components/modal.md
  src/pages/ui-components/components/navigation.md
  src/pages/ui-components/components/tab.md
  src/pages/ui-components/concepts/semantic-configuration.md
Labels: migration
