Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2022-07, with the labels that each got.

#15 Fix grammatical error
  src/pages/guide/css/quickstart/compilation-mode.md
Labels: editorial

#16 Fix missing parenthesis
  src/pages/guide/best-practices.md
Labels: editorial

#12 Update Algolia key names and switch to Yarn v3
  .env.example
  .github/PULL_REQUEST_TEMPLATE.md
  .github/linters/.yaml-lint.yml
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  yarn.lock
Labels: bug, dependencies, enhancement

#26 Updated workflows to serve as standard for devsite templates
  .github/linters/.yaml-lint.yml
  .github/scripts/get-path-prefix.js
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  README.md
  gatsby-config.js
Labels: bug, enhancement

#27 fix: update path to prevent action from creating wrong path
  .github/scripts/get-path-prefix.js
  .github/workflows/deploy.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  .prettierignore
  .prettierrc.yml
Labels: bug

#29 fix: update deployment workflow and clean up
  .github/linters/.yaml-lint.yml
  .github/scripts/get-path-prefix.js
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  .prettierignore
  .prettierrc.yml
  README.md
  gatsby-config.js
Labels: bug, enhancement

#30 Spelling fixes
  src/pages/ui-components/components/checkbox-toggle-notice.md
  src/pages/ui-components/concepts/index.md
  src/pages/ui-components/howto/add-category-attribute.md
  src/pages/ui-components/howto/new-component-declaration.md
Labels: editorial
