Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2023-03, with the labels that each got.

#88 Correct image examples
  src/pages/guide/translations/practice.md
Labels: editorial

#89 Rename magento-devdocs to commerce-docs in links
  src/pages/page-builder/content-types/customize/add-custom-toolbar.md
  src/pages/page-builder/content-types/extend/add-appearances.md
  src/pages/page-builder/content-types/extend/extend-appearances.md
  src/pages/page-builder/content-types/extend/extend-more-appearances.md
  src/pages/page-builder/pagebuilder-examples.md
  src/pages/page-builder/viewports/add-viewports.md
Labels: maintenance

#92 Sync with the required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  CODE_OF_CONDUCT.md
  package.json
  yarn.lock
Labels: maintenance

#93 Prepare for required workflow
  .github/workflows/test-pull-request.yml
Labels: maintenance

#95 Fix deployment issue with memory allocation
  .github/workflows/deploy.yml
Labels: bug

#94 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#99 COMDOX-588: Update issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/incorrect_topic.yaml
  .github/ISSUE_TEMPLATE/missing_content.yaml
  .github/ISSUE_TEMPLATE/site_bug.yaml
  .github/ISSUE_TEMPLATE/site_feature.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
Labels: maintenance

#101 COMDOX-588: Standardized README
  README.md
Labels: maintenance

#103 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: maintenance, dependencies
