Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2023-11, with the labels that each got.

#145 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#143 Correct misspelled word in upgrade-content-types.md
  src/pages/page-builder/upgrade-content-types.md
Labels: editorial

#147 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#149 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#148 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/guide/css/debug.md
  src/pages/page-builder/migration/install-migration-module.md
  src/pages/ui-components/components/columns-controls.md
  src/pages/ui-components/components/file-uploader.md
  yarn.lock
Labels: enhancement
