Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2023-05, with the labels that each got.

#109 Fix Link to Theme Inheritance Docs
  src/pages/guide/css/ui-library.md
Labels: editorial

#113 Add autodeployment
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: enhancement

#115 Convert add-to-project-board to reusable workflow
  .github/workflows/add-to-project-board.yml
Labels: enhancement, maintenance
