Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2023-09, with the labels that each got.

#132 Update index.md
  src/pages/page-builder/architecture/index.md
Labels: editorial

#133 Update jQuery UI version to match the current version
  src/pages/javascript/jquery-widgets/index.md
Labels: editorial

#135 Increase memory to fix indexing workflow failures
  .github/workflows/index.yml
Labels: maintenance

#139 Fix heading typo in ColorPicker UI component topic
  src/pages/ui-components/components/color-picker.md
Labels: editorial, internal

#136 ACP2E-2397: Update documentation for ACP2E-2281
  src/pages/guide/responsive-design/css.md
Labels: technical, internal
