Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2023-07, with the labels that each got.

#98 change uploader path
  src/pages/page-builder/content-types/customize/add-image-uploader.md
Labels: editorial

#117 Update email-migration.md
  src/pages/guide/templates/email-migration.md
Labels: technical

#125 GH-100: Add file to TOC
  src/data/navigation/sections/ui_components.js
  src/pages/ui-components/concepts/xml-configuration.md
Labels: editorial, internal

#124 COMDOX-722: Increased prod deploy job memory
  .github/workflows/publish.yml
Labels: maintenance, internal
