Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2024-08, with the labels that each got.

#180 Add docs explain new flag css trigger static content
  src/pages/guide/css/preprocess.md
Labels: major-update, 2.4.8

#194 Minor formatting for #180
  src/pages/guide/css/preprocess.md
Labels: editorial, internal, 2.4.8

#195 Refactor GitHub Actions workflows
  .github/super-linter.env
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: maintenance, internal
