Repository AdobeDocs/commerce-frontend-core, pull requests merged in 2024-04, with the labels that each got.

#164 Upgrade theme to v4.11.9
  .github/workflows/test-pull-request.yml
  package.json
  src/pages/javascript/index.md
  src/pages/javascript/jquery-widgets/list.md
  yarn.lock
Labels: internal, dependencies

#168 ACP2E-3031: Update the documentation on OM in templates
  src/_includes/objects-in-templates.md
  src/pages/guide/layouts/xml-instructions.md
  src/pages/guide/templates/override.md
Labels: major-update, internal

#170 ACP2E-3031: Update the documentation on OM in templates
  src/pages/guide/layouts/xml-instructions.md
  src/pages/guide/templates/override.md
Labels: editorial, internal

#171 ACP2E-3042: Update the documentation on mobile/ desktop breakpoints (rollback previous changes)
  src/pages/guide/responsive-design/css.md
Labels: technical, internal, 2.4.8
